### ISSUE TITLE
recatpcha

### ISSUE THREAD

**Issue by ulab** [getgrav/grav-plugin-comments#46]
At multiple places in the code and the config file "recatpcha" is used instead of "recaptcha".

While it might work, it feels wrong ;-).

**Comment by flaviocopes** [comment]
I fixed this in the example, in the repository. The wrong spelling was added by mistake when the functionality was added in the first place in a PR, when the problem was noticed it was already shipped, so to avoid causing issues, both will (should) work. 

But all the examples should now use the correct spelling.
